Patch gawk to work under hermetic toolchain
Gawk references its own `support/regex.h` as a sysinclude

```c
#include <regex.h>
```

This is a problem for some toolchains' sysroots which provide their own
`regex.h`, which may or may not provide all the symbols that are
expected. For instance
`external/hermetic_cc_toolchain~~toolchains~zig_config/lib/libc/include/any-macos-any/regex.h`
which when uses causes compilation failures:

```
In file included from external/gawk~/str_array.c:28:
external/gawk~/awk.h:184:27: error: field has incomplete type 'struct re_pattern_buffer'
  184 |         struct re_pattern_buffer pat;
      |                                  ^
external/gawk~/awk.h:184:9: note: forward declaration of 'struct re_pattern_buffer'
  184 |         struct re_pattern_buffer pat;
      |                ^
external/gawk~/awk.h:185:22: error: field has incomplete type 'struct re_registers'
  185 |         struct re_registers regs;
      |                             ^
external/gawk~/awk.h:185:9: note: forward declaration of 'struct re_registers'
  185 |         struct re_registers regs;
      |
```

If we just use quote includes of repo-root-relative paths, things will
work as intended.